sudo: false
language: rust
os:
- linux
- osx
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo --only stable doc
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
after_success:
- travis-cargo --only stable doc-upload
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=dev
  - secure: EIiYteVFFjQKWrr7mcZtx3e42SyKNGOua82ePrbR/kIpULIWz7+D/aCWIgZLD4rz4V1w1Wbhni5bOZkMCitIPonAt2yMPasI7tLjf8mGdiaT9wSKEQdlodvRBjsqI9e9aM9l8xGWxO2GozzVuJwBT8dS6C5mJ7+vCMBafLGF+iNMmyZlrb/XKPESA9eycjLUr/oR1qEF3vpYp+lSPnNtxG9Cnu+vmXd+d7RLR+toXAv3UWtbitw0mcp63t3FYayQFHZ3vMYqMR4K+m5LumPU6y/85zj3ml06WlZuJez3f2E6+Fk8Z8GC22LazffqCkSWvO4YPl6MxJM6Ulz6sNHTC2UlkW60hCOBhzNp5q49KjpgMMpB8frvKxXzE2DultOF88j5BiitzQPrDWDNkJQFoq0gPGROP2rs4NuOOgZhhL145hozZF17BDHxEVLjibXfrgcORec1FQ11Wqcw/ycJZ9TSH43BSEM+5WBs1qC55UifRDJV+WRDjTENWlyBDjRdezf9Zj1k3E6bnuG25yzrF2D6ir4WW2vqdntRzSizX6uZ1R5w1PsarkRIBhOFNDeUrgMB9dP9iMeRi2hrmc2fDAfk+jxBbT4ZsUSSUx4UTar+PdioXIPiTnKnU9FPoCOUbXdwbEYDPbJJVSbs8jTkIW3ZqzNyTKWf5FGg2s92dz0=
